apiVersion: v1
kind: Secret
metadata:
  name: muxiu1997.com
  namespace: muxiu1997-dot-com
type: Opaque
data:
  RCLONE_CONFIG_CONTENT: ""
  BITWARDEN_SMTP_USERNAME: ""
  BITWARDEN_SMTP_PASSWORD: ""
  BITWARDEN_ADMIN_TOKEN: ''
  NPS_PUBLIC_VKEY: ""
  NPS_WEB_USERNAME: ""
  NPS_WEB_PASSWORD: ""
  NPS_AUTH_KEY: ''
  NPS_AUTH_CRYPT_KEY: ""
