# /var/lib/rancher/k3s/server/manifests/traefik-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: traefik-secret
  namespace: kube-system
type: Opaque
data:
  ALICLOUD_ACCESS_KEY: ""
  ALICLOUD_SECRET_KEY: ""
  GITHUB_OAUTH_CLIENT_ID: ""
  GITHUB_OAUTH_CLIENT_SECRET: ""
