# /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  # language=yaml
  valuesContent: |-
    image:
      name: traefik
      tag: v2.9.6
      pullPolicy: IfNotPresent
    hostNetwork: true
    deployment:
      dnsPolicy: ClusterFirstWithHostNet
    ports:
      websecure:
        tls:
          enabled: true
          certResolver: cloudflare
          domains:
            - main: muxiu1997.com
              sans:
                - '*.muxiu1997.com'
      web:
        redirectTo: websecure
    additionalArguments:
      - --certificatesresolvers.cloudflare.acme.email=muxiu1997@gmail.com
      - --certificatesresolvers.cloudflare.acme.storage=/data/acme.json
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --experimental.plugins.github-oauth.modulename=github.com/MuXiu1997/traefik-github-oauth-plugin
      - --experimental.plugins.github-oauth.version=v0.3.0
    env:
      - name: CF_DNS_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: traefik-secret
            key: CF_DNS_API_TOKEN
      - name: TZ
        value: Asia/Shanghai
    persistence:
      enabled: true
      storageClass: local-path
    logs:
      general:
        level: DEBUG
    experimental:
      plugins:
        enabled: true
    ingressRoute:
      dashboard:
        enabled: false
        
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-dashboard-github-oauth
  namespace: kube-system
spec:
  plugin:
    github-oauth:
      apiBaseUrl: http://traefik-github-oauth-server.kube-system
      whitelist:
        logins:
          - MuXiu1997

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: kube-system
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`traefik.muxiu1997.com`)
      services:
        - kind: TraefikService
          name: api@internal
      middlewares:
        - name: traefik-dashboard-github-oauth
