# /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    hostNetwork: true
    ports:
      websecure:
        tls:
          enabled: true
          certResolver: ali
          domains:
            - main: muxiu1997.com
              sans:
                - '*.muxiu1997.com'
      web:
        redirectTo: websecure
    additionalArguments:
      - --certificatesresolvers.ali.acme.email=muxiu1997@gmail.com
      - --certificatesresolvers.ali.acme.storage=/data/acme.json
      - --certificatesresolvers.ali.acme.dnschallenge.provider=alidns
    env:
      - name: ALICLOUD_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: traefik-secret
            key: ALICLOUD_ACCESS_KEY
      - name: ALICLOUD_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: traefik-secret
            key: ALICLOUD_SECRET_KEY
      - name: ALICLOUD_REGION_ID
        value: cn-beijing
      - name: TZ
        value: Asia/Shanghai
    persistence:
      enabled: true
      storageClass: local-path
    logs:
      general:
        level: DEBUG
