version: '3.9'

networks:
  proxy:
    external: true

configs:
  timezone:
    external: true
  localtime:
    external: true

secrets:
  BITWARDEN_SMTP_USERNAME:
    external: true
  BITWARDEN_SMTP_PASSWORD:
    external: true
  BITWARDEN_ADMIN_TOKEN:
    external: true

volumes:
  data: { }

services:
  bitwarden:
    image: vaultwarden/server:1.23.1-alpine
    networks:
      - proxy
    configs:
      - source: timezone
        target: /etc/timezone
      - source: localtime
        target: /etc/localtime
    secrets:
      - BITWARDEN_SMTP_USERNAME
      - BITWARDEN_SMTP_PASSWORD
      - BITWARDEN_ADMIN_TOKEN
    environment:
      DOMAIN: https://bw.muxiu1997.com
      SMTP_HOST: smtp.qq.com
      SMTP_FROM: 765566096@qq.com
      SMTP_FROM_NAME: bitwarden@bw.muxiu1997.com
      SMTP_USERNAME_FILE: /run/secrets/BITWARDEN_SMTP_USERNAME
      SMTP_PASSWORD_FILE: /run/secrets/BITWARDEN_SMTP_PASSWORD
      SMTP_PORT: 465
      SMTP_SSL: 'true'
      SMTP_EXPLICIT_TLS: 'true'
      SMTP_TIMEOUT: 15
      ADMIN_TOKEN_FILE: /run/secrets/BITWARDEN_ADMIN_TOKEN
    volumes:
      - data:/data
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.bitwarden.entrypoints=web, websecure
        - traefik.http.routers.bitwarden.rule=Host(`bw.muxiu1997.com`)
        - traefik.http.services.bitwarden.loadbalancer.server.port=80
