apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "app.fullname" . }}
  namespace: {{ template "app.namespace" . }}
  annotations:
  {{- with .Values.persistence.annotations }}
  {{ toYaml . | nindent 4 }}
  {{- end }}
    helm.sh/resource-policy: keep
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
