apiVersion: v1
kind: Service
metadata:
  name: {{ include "dufs.fullname" . }}
  namespace: {{ template "dufs.namespace" . }}
  labels:
    {{- include "dufs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "dufs.selectorLabels" . | nindent 4 }}
