apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nps
  namespace: muxiu1997-dot-com
spec:
  chart: https://muxiu1997.github.io/cloud-server-services/charts/nps-0.1.0-20230827.tgz
  valuesContent: |-
    namespaceOverride: muxiu1997-dot-com
    nameOverride: nps
    env:
      - name: NPS_RUNMODE
        value: pro
      - name: COMMENT_NPS_HTTPS_PROXY_PORT
        value: 'true'
      - name: COMMENT_NPS_HTTPS_DEFAULT_CERT_FILE
        value: 'true'
      - name: COMMENT_NPS_HTTPS_DEFAULT_KEY_FILE
        value: 'true'
      - name: NPS_PUBLIC_VKEY
        valueFrom:
          secretKeyRef:
            name: muxiu1997.com
            key: NPS_PUBLIC_VKEY
      - name: NPS_WEB_HOST
        value: nps.muxiu1997.com
      - name: NPS_WEB_USERNAME
        valueFrom:
          secretKeyRef:
            name: muxiu1997.com
            key: NPS_WEB_USERNAME
      - name: NPS_WEB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: muxiu1997.com
            key: NPS_WEB_PASSWORD
      - name: COMMENT_NPS_WEB_CERT_FILE
        value: 'true'
      - name: COMMENT_NPS_WEB_KEY_FILE
        value: 'true'
      - name: COMMENT_NPS_AUTH_KEY
        value: ''
      - name: NPS_AUTH_KEY
        valueFrom:
          secretKeyRef:
            name: muxiu1997.com
            key: NPS_AUTH_KEY
      - name: NPS_AUTH_CRYPT_KEY
        valueFrom:
          secretKeyRef:
            name: muxiu1997.com
            key: NPS_AUTH_CRYPT_KEY
      - name: COMMENT_NPS_ALLOW_PORTS
        value: ''
      - name: NPS_ALLOW_PORTS
        value: '14100-14199'
      - name: TZ
        value: Asia/Shanghai
    services:
      bridge:
        type: LoadBalancer
    portTunnels:
      type: LoadBalancer
      ports:
        - start: 14100
          end: 14199
          protocol: TCP
        - start: 14100
          end: 14199
          protocol: UDP
    persistence:
      storageClass: local-path
    traefikWeb:
      entryPoints:
        - web
        - websecure
      defaultRoute:
        match: Host(`nps.muxiu1997.com`)
    traefikHttpTunnel:
      entryPoints:
        - web
        - websecure
      defaultRoute:
        match: HostRegexp(`{subdomain:[A-Za-z0-9_]+}.nps.muxiu1997.com`)
      additionalProperties:
        tls:
          certResolver: cloudflare
          domains:
            - main: nps.muxiu1997.com
              sans:
                - "*.nps.muxiu1997.com" 
                
