api:
  insecure: true

providers:
  docker:
    swarmMode: true
    network: proxy
    exposedByDefault: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          permanent: true
          scheme: https
          to: websecure
  websecure:
    address: :443
    http:
      tls:
        certResolver: ali
        domains:
          - main: muxiu1997.com
            sans:
              - '*.muxiu1997.com'

certificatesResolvers:
  ali:
    acme:
      dnsChallenge:
        provider: alidns
      email: muxiu1997@gmail.com
      storage: /etc/acme/acme.json

accessLog: {}
