version: '3.9'

networks:
  proxy:
    external: true

configs:
  timezone:
    external: true
  localtime:
    external: true

volumes:
  data: {}
  config: {}

services:
  sftpgo:
    image: drakkan/sftpgo:v2.2.1-alpine
    networks:
      - proxy
    configs:
      - source: timezone
        target: /etc/timezone
      - source: localtime
        target: /etc/localtime
    environment:
      SFTPGO_WEBDAVD__BINDINGS__0__PORT: 10080
    volumes:
      - data:/srv/sftpgo
      - config:/var/lib/sftpgo
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.sftpgo.entrypoints=web, websecure
        - traefik.http.routers.sftpgo.rule=Host(`sftp.muxiu1997.com`)
        - traefik.http.routers.sftpgo.service=sftpgo
        - traefik.http.services.sftpgo.loadbalancer.server.port=8080
        - traefik.http.routers.webdav.entrypoints=web, websecure
        - traefik.http.routers.webdav.rule=Host(`webdav.muxiu1997.com`)
        - traefik.http.routers.webdav.service=webdav
        - traefik.http.services.webdav.loadbalancer.server.port=10080
