apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: bitwarden
  namespace: muxiu1997-dot-com
spec:
  chart: https://muxiu1997.github.io/cloud-server-services/charts/simple-web-app-0.1.0.tgz
  # language=yaml
  valuesContent: |-
    name: bitwarden
    version: 1.30.5
    namespaceOverride: muxiu1997-dot-com
    image:
      repository: vaultwarden/server
      tag: 1.30.5-alpine
    livenessProbePath: /alive
    readinessProbePath: /alive
    env:
      - name: DOMAIN
        value: https://bw.muxiu1997.com
      - name: SMTP_HOST
        value: smtp.163.com
      - name: SMTP_FROM
        valueFrom:
          secretKeyRef:
            name: muxiu1997.com
            key: BITWARDEN_SMTP_USERNAME
      - name: SMTP_FROM_NAME
        value: bitwarden@bw.muxiu1997.com
      - name: SMTP_USERNAME
        valueFrom:
          secretKeyRef:
            name: muxiu1997.com
            key: BITWARDEN_SMTP_USERNAME
      - name: SMTP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: muxiu1997.com
            key: BITWARDEN_SMTP_PASSWORD
      - name: SMTP_PORT
        value: "465"
      - name: SMTP_SSL
        value: "true"
      - name: SMTP_EXPLICIT_TLS
        value: "true"
      - name: SMTP_TIMEOUT
        value: "15"
      - name: ADMIN_TOKEN
        valueFrom:
          secretKeyRef:
            name: muxiu1997.com
            key: BITWARDEN_ADMIN_TOKEN
      - name: TZ
        value: Asia/Shanghai
    persistence:
      storageClass: local-path
      size: 128Mi
    traefik:
      entryPoints:
        - web
        - websecure
      defaultRoute:
        match: Host(`bw.muxiu1997.com`)
