apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-bitwarden
  namespace: muxiu1997-dot-com
spec:
  schedule: '0 0 * * *'
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 0
      template:
        spec:
          containers:
            - name: backup-bitwarden
              image: muxiu1997/backup-restore:latest
              env:
                - name: RCLONE_CONFIG_CONTENT
                  valueFrom:
                    secretKeyRef:
                      name: muxiu1997.com
                      key: RCLONE_CONFIG_CONTENT
                - name: BACKUP_NAME
                  value: bitwarden
                - name: REMOTE_BACKUP_DIR
                  value: dropbox:/muxiu1997.com/backup/bitwarden
                - name: GLOB_TO_BE_BACKED_UP
                  value: /data/**
                - name: MAX_BACKUPS
                  value: '30'
                - name: TZ
                  value: Asia/Shanghai
              args:
                - backup
              volumeMounts:
                - name: bitwarden
                  mountPath: /data
          volumes:
            - name: bitwarden
              persistentVolumeClaim:
                claimName: bitwarden
          restartPolicy: Never
