apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-bitwarden
  namespace: muxiu1997-dot-com
spec:
  schedule: '0 0 * * *'
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 2592000 # keep the job for 30 days (60 * 60 * 24 * 30)
      template:
        spec:
          containers:
            - name: backup-bitwarden
              image: muxiu1997/backup-restore:2024-04-02
              env:
                - name: BACKUP_METHOD
                  value: webdav
                - name: REMOTE_BACKUP_DIR
                  value: /muxiu1997.com/bitwarden
                - name: BACKUP_NAME
                  value: bitwarden
                - name: WEBDAV_URL
                  value: http://backup-service
                - name: WEBDAV_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: muxiu1997.com
                      key: BACKUP_WEBDAV_USERNAME
                - name: WEBDAV_PASSWORD
                  valueFrom:
                      secretKeyRef:
                        name: muxiu1997.com
                        key: BACKUP_WEBDAV_PASSWORD
                - name: GLOB_TO_BE_BACKED_UP
                  value: /data/**
                - name: MAX_BACKUPS
                  value: '30'
                - name: TZ
                  value: Asia/Shanghai
              args:
                - backup
              volumeMounts:
                - name: bitwarden
                  mountPath: /data
          volumes:
            - name: bitwarden
              persistentVolumeClaim:
                claimName: bitwarden
          restartPolicy: Never
