version: '3.9'

networks:
  proxy:
    external: true

configs:
  timezone:
    external: true
  localtime:
    external: true

secrets:
  NPS_CONF:
    external: true

volumes:
  data: { }

services:
  nps:
    image: ffdfgdfg/nps:v0.26.10
    ports:
      - '8024:8024'
      - '14100-14115:14100-14115'
      - '14100-14115:14100-14115/udp'
    networks:
      - proxy
    configs:
      - source: timezone
        target: /etc/timezone
      - source: localtime
        target: /etc/localtime
    volumes:
      - data:/conf
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.nps-web.entrypoints=web, websecure
        - traefik.http.routers.nps-web.rule=Host(`nps.muxiu1997.com`)
        - traefik.http.routers.nps-web.service=nps-web
        - traefik.http.services.nps-web.loadbalancer.server.port=8080

        - traefik.http.routers.nps-http.entrypoints=web
        - traefik.http.routers.nps-http.rule=HostRegexp(`{subdomain:[A-Za-z0-9]+}.nps.muxiu1997.com`)
        - traefik.http.routers.nps-http.service=nps-http
        - traefik.http.routers.nps-https.entrypoints=websecure
        - traefik.http.routers.nps-https.rule=HostRegexp(`{subdomain:[A-Za-z0-9]+}.nps.muxiu1997.com`)
        - traefik.http.routers.nps-https.service=nps-http
        - traefik.http.routers.nps-https.tls.certResolver=ali
        - traefik.http.routers.nps-https.tls.domains[0].main=nps.muxiu1997.com
        - traefik.http.routers.nps-https.tls.domains[0].sans=*.nps.muxiu1997.com
        - traefik.http.services.nps-http.loadbalancer.server.port=80
      placement:
        constraints:
          - node.role == manager
