# Default values for bitwarden.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
  
namespaceOverride: ''

replicaCount: 1

image:
  repository: vaultwarden/server
  pullPolicy: IfNotPresent
  alpine: true
  # Overrides the image tag whose default is the chart appVersion.
  tag: ''

imagePullSecrets: [ ]
nameOverride: ''
fullnameOverride: ''

podAnnotations: { }

resources: { }
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: { }

tolerations: [ ]

affinity: { }

env: { }
  # - name: "DOMAIN"
  #   value: "https://example.com"

persistence:
  enabled: true
  name: data
  path: /data
  accessMode: ReadWriteOnce
  storageClass: '' # empty string means use the default storage class
  size: 128Mi
  annotations: { }
  existingClaim: ''

service:
  type: ClusterIP
  port: 80

traefik:
  entryPoints: [ ]
  defaultRoute:
    enabled: true
    match: Host(`example.com`)
    additionalProperties: { }
  additionalRoutes: [ ]
