apiVersion: v1
kind: Service
metadata:
  name: {{ include "bark.fullname" . }}
  namespace: {{ template "bark.namespace" . }}
  labels:
    {{- include "bark.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "bark.selectorLabels" . | nindent 4 }}
