apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: bark
  namespace: muxiu1997-dot-com
spec:
  chart: https://muxiu1997.github.io/cloud-server-services/charts/bark-0.1.0-20240322.tgz
  # language=yaml
  valuesContent: |-
    namespaceOverride: muxiu1997-dot-com
    nameOverride: bark
    env:
      - name: TZ
        value: Asia/Shanghai
    persistence:
      storageClass: local-path
    traefik:
      entryPoints:
        - web
        - websecure
      defaultRoute:
        match: Host(`bark.muxiu1997.com`)
